import type { FoodItem } from "./types"

export const foodItems: FoodItem[] = [
  // Nigerian Foods
  {
    id: "1",
    name: "Jollof Rice with Chicken",
    description:
      "Aromatic Nigerian jollof rice served with grilled chicken, plantain, and coleslaw. A true taste of home!",
    price: 4500,
    image: "/images/jollof-rice.png",
    category: "nigerian",
    available: true,
    preparationTime: 25,
  },
  {
    id: "2",
    name: "Pounded Yam & Egusi Soup",
    description:
      "Traditional pounded yam served with rich egusi soup, assorted meat and fish. Pure Nigerian comfort food.",
    price: 5200,
    image: "/images/pounded-yam-egusi.png",
    category: "nigerian",
    available: true,
    preparationTime: 30,
  },
  {
    id: "3",
    name: "Suya Platter",
    description:
      "Spicy grilled beef suya with onions, tomatoes, and yaji spice. Perfect for sharing or solo indulgence.",
    price: 3800,
    image: "/images/suya-platter.png",
    category: "nigerian",
    available: true,
    preparationTime: 15,
  },
  {
    id: "4",
    name: "Pepper Soup",
    description:
      "Spicy Nigerian pepper soup with assorted meat and traditional spices. Soul-warming goodness in a bowl.",
    price: 3500,
    image: "/images/pepper-soup.png",
    category: "nigerian",
    available: true,
    preparationTime: 20,
  },
  {
    id: "5",
    name: "Amala & Ewedu with Gbegiri",
    description: "Soft amala served with ewedu and gbegiri soup, assorted meat. A Yoruba delicacy that hits different.",
    price: 4800,
    image: "/images/amala-ewedu.png",
    category: "nigerian",
    available: true,
    preparationTime: 25,
  },
  {
    id: "6",
    name: "Ofada Rice & Ayamase Stew",
    description: "Local ofada rice with spicy green pepper stew (ayamase), assorted meat and ponmo. Absolutely divine!",
    price: 5500,
    image: "/images/ofada-rice.png",
    category: "nigerian",
    available: true,
    preparationTime: 30,
  },

  // Fast Food
  {
    id: "7",
    name: "Chicken Burger Combo",
    description: "Crispy chicken burger with lettuce, tomatoes, cheese, served with seasoned fries and a soft drink.",
    price: 3200,
    image: "/images/chicken-burger.png",
    category: "fastfood",
    available: true,
    preparationTime: 12,
  },
  {
    id: "8",
    name: "Beef Shawarma",
    description: "Grilled beef shawarma wrapped in soft pita with vegetables, pickles and our signature sauce.",
    price: 2800,
    image: "/images/beef-shawarma.png",
    category: "fastfood",
    available: true,
    preparationTime: 10,
  },
  {
    id: "9",
    name: "Margherita Pizza (Large)",
    description: "Classic pizza with rich tomato sauce, fresh mozzarella, and aromatic basil leaves. Simply perfect.",
    price: 6500,
    image: "/images/margherita-pizza.png",
    category: "fastfood",
    available: true,
    preparationTime: 18,
  },
  {
    id: "10",
    name: "Fried Chicken & Chips",
    description: "Crispy golden fried chicken pieces served with seasoned potato chips and coleslaw.",
    price: 4200,
    image: "/images/fried-chicken.png",
    category: "fastfood",
    available: true,
    preparationTime: 15,
  },
  {
    id: "11",
    name: "Fish & Chips",
    description: "Beer-battered fish fillet with golden fries, tartar sauce, and a side of mushy peas.",
    price: 4800,
    image: "/images/fish-chips.png",
    category: "fastfood",
    available: true,
    preparationTime: 16,
  },

  // Snacks
  {
    id: "12",
    name: "Meat Pie (2 pieces)",
    description: "Flaky, buttery pastry filled with seasoned minced meat, carrots, and potatoes. A Nigerian classic!",
    price: 1200,
    image: "/images/meat-pie.png",
    category: "snacks",
    available: true,
    preparationTime: 5,
  },
  {
    id: "13",
    name: "Puff Puff (6 pieces)",
    description: "Sweet, fluffy deep-fried dough balls dusted with powdered sugar. Perfect with a cold drink!",
    price: 800,
    image: "/images/puff-puff.png",
    category: "snacks",
    available: true,
    preparationTime: 8,
  },
  {
    id: "14",
    name: "Chin Chin (Pack)",
    description: "Crunchy, sweet fried pastry cubes that melt in your mouth. Addictively delicious!",
    price: 1500,
    image: "/images/chin-chin.png",
    category: "snacks",
    available: true,
    preparationTime: 3,
  },
  {
    id: "15",
    name: "Plantain Chips (Large Pack)",
    description: "Crispy sliced plantain chips, lightly salted and perfectly seasoned. Healthy and tasty!",
    price: 1000,
    image: "/images/plantain-chips.png",
    category: "snacks",
    available: true,
    preparationTime: 5,
  },
  {
    id: "16",
    name: "Samosa (4 pieces)",
    description: "Crispy triangular pastries filled with spiced vegetables and meat. A delightful fusion snack!",
    price: 1600,
    image: "/images/samosa.png",
    category: "snacks",
    available: true,
    preparationTime: 8,
  },
  {
    id: "17",
    name: "Scotch Egg (2 pieces)",
    description:
      "Hard-boiled eggs wrapped in seasoned sausage meat, coated in breadcrumbs and deep-fried to perfection.",
    price: 1800,
    image: "/images/scotch-egg.png",
    category: "snacks",
    available: true,
    preparationTime: 10,
  },
]
